### ISSUE TITLE
Unable to use plugin with Jenkins v2.45(No Option to Add Build Step)

### ISSUE THREAD

**Issue by sudipto1989** [Runscope/runscope-jenkins-plugin#14]
Hi there,
I have added the plugin in Jenkins v2.45, as per the document it says there should be a 'Add build step' in Jenkins Project configuration but I don't see that option in the configuration.
I have few questions:
1. Is the plugin supported by Jenkins v2.45 or not.
2. Is there a new way to setup the plugin to be used in CI wth Jenkins.

Regards,
Sudipto

**Comment by Duncan00** [comment]
Got same problem here~

**Comment by sudipto1989** [comment]
Not an issue anymore
