### ISSUE TITLE
net.sf.json.JSONException: Found starting '{' but missing '}' at the end

### ISSUE THREAD

**Issue by soulfly** [Runscope/runscope-jenkins-plugin#3]
Follow your guide and got 

     API EndPoint: results
     Failed Url request: GET https://api.runscope.com/buckets/dvlgj05gr22o/radar/9a228bd4-xxxx-4e2e- bbc3-eec1f63b25e8/results/xxxxxxx-9830-494f-a167-1645457ee435    HTTP/1.1net.sf.json.JSONException: Found starting '{' but missing '}' at the end. at character 0 of null
     Response received:https://www.runscope.com/radar/dvlgj0hgr22o/2a928bd4-xxxx-4e2e-bbc3-eec1f63b25e8/results/xxxxxxxx-9830-195f-a167-1645457ee4e5
     Build step 'Runscope Test Configuration' changed build result to FAILURE

what can be the issue?

**Comment by mansilladev** [comment]
Hmm.. malformed JSON? Not sure. Has this happened more than once? Sorry for the delayed response. Shoot me an email (neil@runscope.com) and we can take a closer look.

**Comment by soulfly** [comment]
It happens all the time, 

we just installed the plugin and trying to use it
